NoClassDefFoundError after upgrading to SonarQube 9 sonar-plugin-api no longer provides the necessary XML libraries, resulting in java.lang.NoClassDefFoundError: com/ctc/wstx/stax/WstxInputFactory